/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Goal {
  'achieved' : boolean,
  'streak' : bigint,
  'progress' : number,
  'targetType' : GoalType,
  'targetHours' : number,
}
export type GoalType = { 'Daily' : null };
export type Time = bigint;
export interface TimerPreset {
  'duration' : bigint,
  'colorTheme' : string,
  'labelText' : string,
}
export interface TimerSession {
  'startTime' : Time,
  'duration' : bigint,
  'endTime' : Time,
  'colorTheme' : string,
  'tags' : Array<string>,
  'labelText' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'exportGoals' : ActorMethod<[], Array<Goal>>,
  'exportPresets' : ActorMethod<[], Array<TimerPreset>>,
  'exportSessions' : ActorMethod<[], Array<TimerSession>>,
  'getAllPresets' : ActorMethod<[], Array<TimerPreset>>,
  'getAllTags' : ActorMethod<[], Array<string>>,
  'getAllWallpapers' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getAverageSessionDuration' : ActorMethod<[], number>,
  'getSessionCount' : ActorMethod<[], bigint>,
  'getSessionsByLabel' : ActorMethod<[string], Array<TimerSession>>,
  'getSessionsByTag' : ActorMethod<[string], Array<TimerSession>>,
  'getWallpaper' : ActorMethod<[string], [] | [ExternalBlob]>,
  'listWallpapers' : ActorMethod<[], Array<string>>,
  'recordSession' : ActorMethod<
    [Time, Time, [] | [string], [] | [string], [] | [Array<string>]],
    undefined
  >,
  'savePreset' : ActorMethod<[string, bigint, string, string], undefined>,
  'setGoal' : ActorMethod<[string, GoalType, number], undefined>,
  'updateGoalProgress' : ActorMethod<[string, number], undefined>,
  'uploadWallpaper' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];