/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GoalType = IDL.Variant({ 'Daily' : IDL.Null });
export const Goal = IDL.Record({
  'achieved' : IDL.Bool,
  'streak' : IDL.Nat,
  'progress' : IDL.Float64,
  'targetType' : GoalType,
  'targetHours' : IDL.Float64,
});
export const TimerPreset = IDL.Record({
  'duration' : IDL.Int,
  'colorTheme' : IDL.Text,
  'labelText' : IDL.Text,
});
export const Time = IDL.Int;
export const TimerSession = IDL.Record({
  'startTime' : Time,
  'duration' : IDL.Int,
  'endTime' : Time,
  'colorTheme' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'labelText' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'exportGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'exportPresets' : IDL.Func([], [IDL.Vec(TimerPreset)], ['query']),
  'exportSessions' : IDL.Func([], [IDL.Vec(TimerSession)], ['query']),
  'getAllPresets' : IDL.Func([], [IDL.Vec(TimerPreset)], ['query']),
  'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllWallpapers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getAverageSessionDuration' : IDL.Func([], [IDL.Float64], ['query']),
  'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSessionsByLabel' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimerSession)],
      ['query'],
    ),
  'getSessionsByTag' : IDL.Func([IDL.Text], [IDL.Vec(TimerSession)], ['query']),
  'getWallpaper' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'listWallpapers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'recordSession' : IDL.Func(
      [
        Time,
        Time,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [],
      [],
    ),
  'savePreset' : IDL.Func([IDL.Text, IDL.Int, IDL.Text, IDL.Text], [], []),
  'setGoal' : IDL.Func([IDL.Text, GoalType, IDL.Float64], [], []),
  'updateGoalProgress' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'uploadWallpaper' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GoalType = IDL.Variant({ 'Daily' : IDL.Null });
  const Goal = IDL.Record({
    'achieved' : IDL.Bool,
    'streak' : IDL.Nat,
    'progress' : IDL.Float64,
    'targetType' : GoalType,
    'targetHours' : IDL.Float64,
  });
  const TimerPreset = IDL.Record({
    'duration' : IDL.Int,
    'colorTheme' : IDL.Text,
    'labelText' : IDL.Text,
  });
  const Time = IDL.Int;
  const TimerSession = IDL.Record({
    'startTime' : Time,
    'duration' : IDL.Int,
    'endTime' : Time,
    'colorTheme' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'labelText' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'exportGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'exportPresets' : IDL.Func([], [IDL.Vec(TimerPreset)], ['query']),
    'exportSessions' : IDL.Func([], [IDL.Vec(TimerSession)], ['query']),
    'getAllPresets' : IDL.Func([], [IDL.Vec(TimerPreset)], ['query']),
    'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllWallpapers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getAverageSessionDuration' : IDL.Func([], [IDL.Float64], ['query']),
    'getSessionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSessionsByLabel' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimerSession)],
        ['query'],
      ),
    'getSessionsByTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimerSession)],
        ['query'],
      ),
    'getWallpaper' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'listWallpapers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'recordSession' : IDL.Func(
        [
          Time,
          Time,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [],
        [],
      ),
    'savePreset' : IDL.Func([IDL.Text, IDL.Int, IDL.Text, IDL.Text], [], []),
    'setGoal' : IDL.Func([IDL.Text, GoalType, IDL.Float64], [], []),
    'updateGoalProgress' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'uploadWallpaper' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };